{
 "title": "Netflow Exporter Overview",
 "description": "Show a Summary from Netflow Exporter Devices",
 "tags": [
  "netflow",
  "nfcollector",
  "exporter",
  "overview"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Interval",
    "label": "Group By Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "nfExporter",
    "label": "Netflow Exporter",
    "query": "SHOW TAG VALUES from sum_proto WITH KEY=ExpHost"
   },
   {
    "name": "ProtoName",
    "label": "Protocol",
    "query": "SHOW TAG VALUES from sum_proto WITH KEY=ProtoName  WHERE ExpHost=~/^$nfExporter$/"
   },
   { "name": "TopVal", "label": "Top", "query": "5,10,20,50" }
  ]
 },
 "panels": [
  {
   "title": "$ProtoName",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "repeat": "ProtoName",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ProtoName" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "sum_proto",
     "query": "from(bucket: \"netflow\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netflow\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"in_bytes\")\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)\r\n  |> yield(name: \"in_bytes_per_minute\")\r\n",
     "select": [
      [
       { "params": [ "Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "Packets" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Packets" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ExpHost", "operator": "=~", "value": "/^$nfExporter$/" },
      { "condition": "AND", "key": "ProtoName", "operator": "=~", "value": "/^$ProtoName$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Src Host",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "srcData = from(bucket: \"netflow\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netflow\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"src\"])\r\n  |> sum(column: \"in_bytes\")\r\n  |> map(fn: (r) => ({ r with group: r.src }))\r\n  |> keep(columns: [\"group\", \"in_bytes\", \"type\"])\r\n\r\ndstData = from(bucket: \"netflow\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netflow\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"dst\"])\r\n  |> sum(column: \"in_bytes\")\r\n  |> map(fn: (r) => ({ r with group: r.dst }))\r\n  |> keep(columns: [\"group\", \"in_bytes\", \"type\"])\r\n\r\nunion(tables: [srcData, dstData])\r\n  |> sort(columns: [\"in_bytes\"], desc: true)\r\n  |> limit(n: 20)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Src Port",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"netflow\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"netflow\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"_time\", \"src\", \"src_port\", \"dst\", \"dst_port\", \"in_bytes\", \"protocol\"])\r\n  |> sort(columns: [\"in_bytes\"], desc: true)\r\n  |> limit(n: 10)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}